var r={ADDRESS:"proofi_address",EMAIL:"proofi_email",TOKEN:"proofi_token",CONNECTED:"proofi_connected"},h="https://proofi-api-production.up.railway.app";function i(){chrome.windows.create({url:chrome.runtime.getURL("popup.html"),type:"popup",width:400,height:600,focused:!0})}chrome.runtime.onMessage.addListener((a,l,o)=>{if(a.type==="GET_WALLET_STATE")return chrome.storage.local.get(Object.values(r),t=>{o({address:t[r.ADDRESS]||null,email:t[r.EMAIL]||null,token:t[r.TOKEN]||null,connected:t[r.CONNECTED]||!1})}),!0;if(a.type==="OPEN_LOGIN_POPUP")return chrome.action?.openPopup?chrome.action.openPopup().then(()=>{o({ok:!0,method:"popup"})}).catch(t=>{console.warn("[Proofi] openPopup() failed, falling back to window:",t.message),i(),o({ok:!0,method:"window"})}):(i(),o({ok:!0,method:"window"})),!0;if(a.type==="SIGN_MESSAGE"){let{message:t,requestId:u}=a;return(async()=>{try{
// Open popup window so user can enter PIN if wallet is locked
let w;try{if(chrome.action?.openPopup){await chrome.action.openPopup()}else{w=await chrome.windows.create({url:chrome.runtime.getURL("popup.html"),type:"popup",width:400,height:600,focused:!0})}}catch(e){w=await chrome.windows.create({url:chrome.runtime.getURL("popup.html"),type:"popup",width:400,height:600,focused:!0})}
// Wait briefly for popup to initialize, then send sign request
// Poll popup until it responds or timeout
let attempts=0,maxAttempts=120;function trySend(){return new Promise((resolve,reject)=>{function attempt(){chrome.runtime.sendMessage({type:"PROOFI_SIGN_MESSAGE",message:t,requestId:u},n=>{if(chrome.runtime.lastError){if(++attempts<maxAttempts){setTimeout(attempt,1000)}else{reject(new Error("Popup did not respond"))}}else{resolve(n)}});} attempt();})}
let result=await trySend();
if(result&&result.signature){o({signature:result.signature})}else if(result&&result.error){o({error:result.error})}else{o({error:"Signing failed"})}
}catch(e){o({error:e.message||"Signing failed"})}})(),!0}if(a.type==="API_REQUEST"){let{path:t,method:u,body:n,authHeaders:p}=a,d={"Content-Type":"application/json",...p||{}};return fetch(`${h}${t}`,{method:u||"GET",headers:d,body:n?JSON.stringify(n):void 0}).then(async e=>{let c=await e.json();e.ok?o({data:c,status:e.status}):o({error:c.error||`API error: ${e.status}`,status:e.status})}).catch(e=>{o({error:e.message,status:0})}),!0}});
