/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/vault` | `/vault`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/pin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/vault` | `/vault`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/pin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/game${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/vault${`?${string}` | `#${string}` | ''}` | `/vault${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/pin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/vault` | `/vault`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; };
    }
  }
}
